### PR TITLE
Fix typos in Section 2 equations

### PR DESCRIPTION
**Pull request by lrapetti**
Fixing typos described in https://github.com/traversaro/phd-thesis/issues/6 and https://github.com/traversaro/phd-thesis/issues/7

### CODE REVIEW

**Comment by lrapetti** [comment]
cc @traversaro @prashanthr05

**Review by prashanthr05 — APPROVED** [review]
LGTM! Thanks for the changes!

**Review by traversaro — APPROVED** [review]
Thanks @lrapetti  and sorry for the delay.

**Comment by traversaro** [comment]
I updated the changelog in https://github.com/traversaro/phd-thesis/pull/19/commits/9bb34b9198dba6a62f454cd11eef303b4dddb499 .

**Pull request merged**
